-- Conectar como SYSTEM
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Crear un único usuario para toda la aplicación
CREATE USER GESTION_LAB_APP IDENTIFIED BY "GESTION_LAB123";

-- Otorgar privilegios necesarios
GRANT CONNECT, RESOURCE TO GESTION_LAB_APP;
GRANT CREATE SESSION TO GESTION_LAB_APP;
GRANT CREATE TABLE TO GESTION_LAB_APP;
GRANT CREATE SEQUENCE TO GESTION_LAB_APP;
GRANT CREATE VIEW TO GESTION_LAB_APP;
GRANT CREATE PROCEDURE TO GESTION_LAB_APP;
GRANT CREATE TRIGGER TO GESTION_LAB_APP;

-- Otorgar cuota ilimitada en el tablespace por defecto
ALTER USER GESTION_LAB_APP QUOTA UNLIMITED ON USERS;

-- Confirmar la creación
SELECT username FROM dba_users WHERE username = 'GESTION_LAB_APP';